### ISSUE TITLE
编译之后没有common.js？

### ISSUE THREAD

**Issue by yezishan** [krhougs/mina-webpack-plugin#2]
为啥编译之后没有common.js文件呢？SplitChunksPlugin没起作用吗？

**Comment by krhougs** [comment]
是报错缺少common.js这个文件吗？

**Comment by yezishan** [comment]
> 是报错缺少common.js这个文件吗？
没有报错，但是编译之后没有把公共的代码抽取到common.js文件里面呀，

**Comment by krhougs** [comment]
`SplitChunksPlugin` 只在所引用的代码同时被多个 entry 所引用时有效。

外部库（node_modules）会被抽取到 `vendor.js`。
你的项目里的公共代码会被抽取到 `common.js`
